"""
Django settings for gym_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-4yj)609$72ppy!&e527=wsgm9+_sasg^3^)r263)ykovwj_c(r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config('ALLOWED_HOSTS', default='192.168.0.156,127.0.0.1,localhost,gym-membership-system-chatbot.onrender.com,.onrender.com').split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gym_app',  # Added gym_app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Added templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support both SQLite (development) and PostgreSQL (production)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production: PostgreSQL on Render
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Custom User Model
AUTH_USER_MODEL = 'gym_app.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'  # Changed to Philippines timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if os.path.exists(os.path.join(BASE_DIR, 'static')):
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATICFILES_DIRS = []

# WhiteNoise compression for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ==================== Caching Configuration ====================
# Redis caching for improved chatbot performance
# To use Redis: pip install redis django-redis
# Then uncomment the Redis configuration below

# Option 1: Redis Cache (Recommended for production)
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'SOCKET_CONNECT_TIMEOUT': 5,
#             'SOCKET_TIMEOUT': 5,
#             'CONNECTION_POOL_KWARGS': {'max_connections': 50},
#             'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
#             'IGNORE_EXCEPTIONS': True,  # Fallback to DB if Redis fails
#         },
#         'KEY_PREFIX': 'gym_chatbot',
#         'TIMEOUT': 300,  # Default timeout 5 minutes
#     }
# }

# Option 2: In-Memory Cache (Current - Good for development)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Option 3: Database Cache (Fallback if Redis not available)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'chatbot_cache_table',
#     }
# }

# ==================== Session Configuration ====================
# Use cache for sessions (faster than database)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# ==================== Chatbot Performance Settings ====================
# Powered by Groq API (FREE - llama-3.3-70b-versatile)

# Groq Configuration (Required - FREE API)
GROQ_API_KEY = config('GROQ_API_KEY', default=None)

# Chatbot Model Parameters
CHATBOT_MODEL = 'llama-3.3-70b-versatile'  # Groq's fast, FREE model
CHATBOT_TEMPERATURE = 0.7  # Creativity level (0.0-1.0)
CHATBOT_TOP_P = 0.9  # Nucleus sampling
CHATBOT_MAX_TOKENS = 500  # Maximum response length in tokens (increased for detailed recommendations)
CHATBOT_CONTEXT_WINDOW = 6  # Messages to keep in context
CHATBOT_ENABLE_STREAMING = False  # Streaming responses disabled
CHATBOT_ENABLE_PERSISTENCE = True  # Save conversation history

# Chatbot Performance Tuning
CHATBOT_CACHE_DURATION_SHORT = 120  # 2 minutes
CHATBOT_CACHE_DURATION_MEDIUM = 600  # 10 minutes
CHATBOT_CACHE_DURATION_LONG = 3600  # 1 hour

# Query Optimization
CHATBOT_MAX_SEARCH_RESULTS = 10  # Limit search results for performance
CHATBOT_ANALYTICS_CACHE_ENABLED = True

# Enhanced Database Context for Recommendations
CHATBOT_ENABLE_GYM_INSIGHTS = True  # Include gym trends and analytics in context
CHATBOT_ENABLE_PERSONALIZED_INSIGHTS = True  # Include member-specific workout recommendations