# Generated by Django 5.2.7 on 2025-11-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_chatbotconfig_conversation_conversationmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='active_model',
            field=models.CharField(choices=[('llama3.2:1b', 'Llama 3.2 1B (Fastest, 8GB RAM)'), ('llama3.2:3b', 'Llama 3.2 3B (Balanced, 12GB RAM)'), ('phi3:3.8b', 'Phi 3 3.8B (Efficient, 12GB RAM)'), ('gemma2:2b', 'Gemma 2 2B (Fast, 8GB RAM)'), ('mistral:7b', 'Mistral 7B (High Quality, 16GB RAM)'), ('qwen2:1.5b', 'Qwen 2 1.5B (Multilingual, 8GB RAM)'), ('qwen2:7b', 'Qwen 2 7B (Advanced Multilingual, 16GB RAM)'), ('qwen2.5:7b', 'Qwen 2.5 7B (Latest, 16GB RAM)'), ('qwenqwen2.5:0.5b', 'Ultra-fast responses (4GB RAM)')], default='llama3.2:1b', help_text='Current active Ollama model', max_length=50),
        ),
        migrations.CreateModel(
            name='GymGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Gallery image (Recommended: 800x600px)', upload_to='gallery/')),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('facility', 'Facility'), ('classes', 'Classes'), ('members', 'Members'), ('events', 'Events'), ('other', 'Other')], default='facility', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gym_gallery',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for the hero section', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subheading or tagline', max_length=300, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('background_image', models.ImageField(help_text='Main background image for hero section (Recommended: 1920x1080px)', upload_to='hero_images/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image (Recommended: 768x1024px)', null=True, upload_to='hero_images/mobile/')),
                ('cta_primary_text', models.CharField(default='Join Now', help_text='Text for primary CTA button', max_length=100)),
                ('cta_primary_link', models.CharField(default='/register/', help_text='URL for primary CTA button', max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, help_text='Text for secondary CTA button (optional)', max_length=100, null=True)),
                ('cta_secondary_link', models.CharField(blank=True, help_text='URL for secondary CTA button', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this hero section on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Overlay darkness (0.0 = transparent, 1.0 = full black)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'db_table': 'hero_sections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
