# Generated by Django 5.2.7 on 2025-11-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_add_chatbot_optimization_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analytics',
            name='analytics_date_sales_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_user_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_method_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermembership',
            name='membership_status_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermembership',
            name='membership_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='walkinpayment',
            name='walkin_date_method_idx',
        ),
    ]
